export const PROGRAMS = [
  "All",
  "AA",
  "NA",
  "SA",
  "SLAA",
  "OA",
  "Al-Anon",
  "CoDA",
];

export const MOCK_SPONSORS = [
  {
    id: 1,
    name: "Michael T.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MichaelT",
    programs: ["AA"],
    sobrietyDate: "2015-04-12",
    location: "Virtual / New York, NY",
    gender: "Male",
    bio: "Hi, I'm Michael. I've been working the steps for 8 years and sponsoring for 5. I believe in a Big Book focused approach, rigorous honesty, and daily contact. I am available for weekly step work and daily check-ins.",
    availability: "Taking new sponsees",
    stepExperience: "Has worked all 12 steps multiple times.",
  },
  {
    id: 2,
    name: "Sarah W.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahW",
    programs: ["AA", "Al-Anon"],
    sobrietyDate: "2018-11-01",
    location: "Virtual Only",
    gender: "Female",
    bio: "Recovery gave me my life back. I sponsor women in AA and Al-Anon. My approach is gentle but firm, focusing on spiritual progress rather than spiritual perfection.",
    availability: "Taking 1 new sponsee",
    stepExperience: "Currently on Step 10/11/12 maintenance.",
  },
  {
    id: 3,
    name: "David K.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DavidK",
    programs: ["SA", "SLAA"],
    sobrietyDate: "2020-02-14",
    location: "Chicago, IL / Virtual",
    gender: "Male",
    bio: "I carry the message of recovery from lust and sex addiction. I require my sponsees to attend at least 3 meetings a week and call me regularly. Willing to read the White Book together.",
    availability: "Taking new sponsees",
    stepExperience: "Has completed the steps.",
  },
  {
    id: 4,
    name: "Elena R.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ElenaR",
    programs: ["NA"],
    sobrietyDate: "2010-08-30",
    location: "Los Angeles, CA",
    gender: "Female",
    bio: "Clean and serene. I focus on the NA Basic Text and how to apply the spiritual principles of the program to everyday life. No matter what, we don't pick up.",
    availability: "Full (Not taking sponsees currently)",
    stepExperience: "Has worked all 12 steps.",
  },
  {
    id: 5,
    name: "James L.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JamesL",
    programs: ["OA"],
    sobrietyDate: "2021-05-10",
    location: "Virtual Only",
    gender: "Male",
    bio: "Abstinent from my bottom-line behaviors for 2 years. I work the OA 12 steps and 12 traditions. Looking for sponsees who are ready to get honest about their food and willing to go to any lengths.",
    availability: "Taking new sponsees",
    stepExperience: "Working the steps with my own sponsor.",
  },
];
